[
  {
    identifier: "com.apple.voice.compact.ar-001.Maged",
    language: "ar-001",
    name: "Majed",
    quality: "Default",
  },
  {
    identifier: "com.apple.voice.compact.bg-BG.Daria",
    language: "bg-BG",
    name: "Daria",
    quality: "Default",
  },
  {
    identifier: "com.apple.voice.compact.ca-ES.Montserrat",
    language: "ca-ES",
    name: "Montse",
    quality: "Default",
  },
  {
    identifier: "com.apple.voice.compact.cs-CZ.Zuzana",
    language: "cs-CZ",
    name: "Zuzana",
    quality: "Default",
  },
  {
    identifier: "com.apple.voice.compact.da-DK.Sara",
    language: "da-DK",
    name: "Sara",
    quality: "Default",
  },
  {
    identifier: "com.apple.eloquence.de-DE.Sandy",
    language: "de-DE",
    name: "Sandy",
    quality: "Default",
  },
  {
    identifier: "com.apple.eloquence.de-DE.Shelley",
    language: "de-DE",
    name: "Shelley",
    quality: "Default",
  },
  {
    identifier: "com.apple.ttsbundle.siri_Helena_de-DE_compact",
    language: "de-DE",
    name: "Helena",
    quality: "Default",
  },
  {
    identifier: "com.apple.eloquence.de-DE.Grandma",
    language: "de-DE",
    name: "Grandma",
    quality: "Default",
  },
  {
    identifier: "com.apple.eloquence.de-DE.Grandpa",
    language: "de-DE",
    name: "Grandpa",
    quality: "Default",
  },
  {
    identifier: "com.apple.eloquence.de-DE.Eddy",
    language: "de-DE",
    name: "Eddy",
    quality: "Default",
  },
  {
    identifier: "com.apple.eloquence.de-DE.Reed",
    language: "de-DE",
    name: "Reed",
    quality: "Default",
  },
  {
    identifier: "com.apple.voice.compact.de-DE.Anna",
    language: "de-DE",
    name: "Anna",
    quality: "Default",
  },
  {
    identifier: "com.apple.ttsbundle.siri_Martin_de-DE_compact",
    language: "de-DE",
    name: "Martin",
    quality: "Default",
  },
  {
    identifier: "com.apple.eloquence.de-DE.Rocko",
    language: "de-DE",
    name: "Rocko",
    quality: "Default",
  },
  {
    identifier: "com.apple.eloquence.de-DE.Flo",
    language: "de-DE",
    name: "Flo",
    quality: "Default",
  },
  {
    identifier: "com.apple.voice.compact.el-GR.Melina",
    language: "el-GR",
    name: "Melina",
    quality: "Default",
  },
  {
    identifier: "com.apple.ttsbundle.Lee-premium",
    language: "en-AU",
    name: "Lee (Enhanced)",
    quality: "Enhanced",
  },
  {
    identifier: "com.apple.ttsbundle.siri_Gordon_en-AU_compact",
    language: "en-AU",
    name: "Gordon",
    quality: "Default",
  },
  {
    identifier: "com.apple.voice.compact.en-AU.Karen",
    language: "en-AU",
    name: "Karen",
    quality: "Default",
  },
  {
    identifier: "com.apple.ttsbundle.Lee-compact",
    language: "en-AU",
    name: "Lee",
    quality: "Default",
  },
  {
    identifier: "com.apple.ttsbundle.siri_Catherine_en-AU_compact",
    language: "en-AU",
    name: "Catherine",
    quality: "Default",
  },
  {
    identifier: "com.apple.ttsbundle.Serena-premium",
    language: "en-GB",
    name: "Serena (Enhanced)",
    quality: "Enhanced",
  },
  {
    identifier: "com.apple.ttsbundle.Kate-premium",
    language: "en-GB",
    name: "Kate (Enhanced)",
    quality: "Enhanced",
  },
  {
    identifier: "com.apple.ttsbundle.Oliver-premium",
    language: "en-GB",
    name: "Oliver (Enhanced)",
    quality: "Enhanced",
  },
  {
    identifier: "com.apple.eloquence.en-GB.Rocko",
    language: "en-GB",
    name: "Rocko",
    quality: "Default",
  },
  {
    identifier: "com.apple.eloquence.en-GB.Shelley",
    language: "en-GB",
    name: "Shelley",
    quality: "Default",
  },
  {
    identifier: "com.apple.ttsbundle.Oliver-compact",
    language: "en-GB",
    name: "Oliver",
    quality: "Default",
  },
  {
    identifier: "com.apple.voice.compact.en-GB.Daniel",
    language: "en-GB",
    name: "Daniel",
    quality: "Default",
  },
  {
    identifier: "com.apple.ttsbundle.siri_Martha_en-GB_compact",
    language: "en-GB",
    name: "Martha",
    quality: "Default",
  },
  {
    identifier: "com.apple.eloquence.en-GB.Grandma",
    language: "en-GB",
    name: "Grandma",
    quality: "Default",
  },
  {
    identifier: "com.apple.eloquence.en-GB.Grandpa",
    language: "en-GB",
    name: "Grandpa",
    quality: "Default",
  },
  {
    identifier: "com.apple.eloquence.en-GB.Flo",
    language: "en-GB",
    name: "Flo",
    quality: "Default",
  },
  {
    identifier: "com.apple.eloquence.en-GB.Eddy",
    language: "en-GB",
    name: "Eddy",
    quality: "Default",
  },
  {
    identifier: "com.apple.ttsbundle.Serena-compact",
    language: "en-GB",
    name: "Serena",
    quality: "Default",
  },
  {
    identifier: "com.apple.ttsbundle.Kate-compact",
    language: "en-GB",
    name: "Kate",
    quality: "Default",
  },
  {
    identifier: "com.apple.eloquence.en-GB.Reed",
    language: "en-GB",
    name: "Reed",
    quality: "Default",
  },
  {
    identifier: "com.apple.eloquence.en-GB.Sandy",
    language: "en-GB",
    name: "Sandy",
    quality: "Default",
  },
  {
    identifier: "com.apple.ttsbundle.siri_Arthur_en-GB_compact",
    language: "en-GB",
    name: "Arthur",
    quality: "Default",
  },
  {
    identifier: "com.apple.voice.compact.en-IE.Moira",
    language: "en-IE",
    name: "Moira",
    quality: "Default",
  },
  {
    identifier: "com.apple.voice.compact.en-IN.Rishi",
    language: "en-IN",
    name: "Rishi",
    quality: "Default",
  },
  {
    identifier: "com.apple.ttsbundle.siri_Nicky_en-US_premium",
    language: "en-US",
    name: "Nicky (Enhanced)",
    quality: "Enhanced",
  },
  {
    identifier: "com.apple.ttsbundle.Allison-premium",
    language: "en-US",
    name: "Allison (Enhanced)",
    quality: "Enhanced",
  },
  {
    identifier: "com.apple.ttsbundle.Ava-premium",
    language: "en-US",
    name: "Ava (Enhanced)",
    quality: "Enhanced",
  },
  {
    identifier: "com.apple.ttsbundle.Susan-premium",
    language: "en-US",
    name: "Susan (Enhanced)",
    quality: "Enhanced",
  },
  {
    identifier: "com.apple.ttsbundle.Allison-compact",
    language: "en-US",
    name: "Allison",
    quality: "Default",
  },
  {
    identifier: "com.apple.eloquence.en-US.Flo",
    language: "en-US",
    name: "Flo",
    quality: "Default",
  },
  {
    identifier: "com.apple.speech.synthesis.voice.Albert",
    language: "en-US",
    name: "Albert",
    quality: "Default",
  },
  {
    identifier: "com.apple.speech.synthesis.voice.Bahh",
    language: "en-US",
    name: "Bahh",
    quality: "Default",
  },
  {
    identifier: "com.apple.speech.synthesis.voice.Fred",
    language: "en-US",
    name: "Fred",
    quality: "Default",
  },
  {
    identifier: "com.apple.speech.synthesis.voice.Hysterical",
    language: "en-US",
    name: "Jester",
    quality: "Default",
  },
  {
    identifier: "com.apple.speech.synthesis.voice.Organ",
    language: "en-US",
    name: "Organ",
    quality: "Default",
  },
  {
    identifier: "com.apple.speech.synthesis.voice.Victoria",
    language: "en-US",
    name: "Victoria",
    quality: "Default",
  },
  {
    identifier: "com.apple.speech.synthesis.voice.Cellos",
    language: "en-US",
    name: "Cellos",
    quality: "Default",
  },
  {
    identifier: "com.apple.speech.synthesis.voice.Zarvox",
    language: "en-US",
    name: "Zarvox",
    quality: "Default",
  },
  {
    identifier: "com.apple.eloquence.en-US.Rocko",
    language: "en-US",
    name: "Rocko",
    quality: "Default",
  },
  {
    identifier: "com.apple.eloquence.en-US.Shelley",
    language: "en-US",
    name: "Shelley",
    quality: "Default",
  },
  {
    identifier: "com.apple.speech.synthesis.voice.Princess",
    language: "en-US",
    name: "Superstar",
    quality: "Default",
  },
  {
    identifier: "com.apple.eloquence.en-US.Grandma",
    language: "en-US",
    name: "Grandma",
    quality: "Default",
  },
  {
    identifier: "com.apple.eloquence.en-US.Eddy",
    language: "en-US",
    name: "Eddy",
    quality: "Default",
  },
  {
    identifier: "com.apple.speech.synthesis.voice.Bells",
    language: "en-US",
    name: "Bells",
    quality: "Default",
  },
  {
    identifier: "com.apple.eloquence.en-US.Grandpa",
    language: "en-US",
    name: "Grandpa",
    quality: "Default",
  },
  {
    identifier: "com.apple.speech.synthesis.voice.Trinoids",
    language: "en-US",
    name: "Trinoids",
    quality: "Default",
  },
  {
    identifier: "com.apple.speech.synthesis.voice.Kathy",
    language: "en-US",
    name: "Kathy",
    quality: "Default",
  },
  {
    identifier: "com.apple.eloquence.en-US.Reed",
    language: "en-US",
    name: "Reed",
    quality: "Default",
  },
  {
    identifier: "com.apple.speech.synthesis.voice.Boing",
    language: "en-US",
    name: "Boing",
    quality: "Default",
  },
  {
    identifier: "com.apple.speech.synthesis.voice.Whisper",
    language: "en-US",
    name: "Whisper",
    quality: "Default",
  },
  {
    identifier: "com.apple.speech.synthesis.voice.GoodNews",
    language: "en-US",
    name: "Good News",
    quality: "Default",
  },
  {
    identifier: "com.apple.speech.synthesis.voice.Deranged",
    language: "en-US",
    name: "Wobble",
    quality: "Default",
  },
  {
    identifier: "com.apple.ttsbundle.siri_Nicky_en-US_compact",
    language: "en-US",
    name: "Nicky",
    quality: "Default",
  },
  {
    identifier: "com.apple.speech.synthesis.voice.BadNews",
    language: "en-US",
    name: "Bad News",
    quality: "Default",
  },
  {
    identifier: "com.apple.ttsbundle.siri_Aaron_en-US_compact",
    language: "en-US",
    name: "Aaron",
    quality: "Default",
  },
  {
    identifier: "com.apple.speech.synthesis.voice.Bubbles",
    language: "en-US",
    name: "Bubbles",
    quality: "Default",
  },
  {
    identifier: "com.apple.voice.compact.en-US.Samantha",
    language: "en-US",
    name: "Samantha",
    quality: "Default",
  },
  {
    identifier: "com.apple.eloquence.en-US.Sandy",
    language: "en-US",
    name: "Sandy",
    quality: "Default",
  },
  {
    identifier: "com.apple.speech.synthesis.voice.Junior",
    language: "en-US",
    name: "Junior",
    quality: "Default",
  },
  {
    identifier: "com.apple.ttsbundle.Susan-compact",
    language: "en-US",
    name: "Susan",
    quality: "Default",
  },
  {
    identifier: "com.apple.ttsbundle.Ava-compact",
    language: "en-US",
    name: "Ava",
    quality: "Default",
  },
  {
    identifier: "com.apple.speech.synthesis.voice.Ralph",
    language: "en-US",
    name: "Ralph",
    quality: "Default",
  },
  {
    identifier: "com.apple.voice.compact.en-ZA.Tessa",
    language: "en-ZA",
    name: "Tessa",
    quality: "Default",
  },
  {
    identifier: "com.apple.eloquence.es-ES.Shelley",
    language: "es-ES",
    name: "Shelley",
    quality: "Default",
  },
  {
    identifier: "com.apple.eloquence.es-ES.Grandma",
    language: "es-ES",
    name: "Grandma",
    quality: "Default",
  },
  {
    identifier: "com.apple.eloquence.es-ES.Rocko",
    language: "es-ES",
    name: "Rocko",
    quality: "Default",
  },
  {
    identifier: "com.apple.eloquence.es-ES.Grandpa",
    language: "es-ES",
    name: "Grandpa",
    quality: "Default",
  },
  {
    identifier: "com.apple.eloquence.es-ES.Sandy",
    language: "es-ES",
    name: "Sandy",
    quality: "Default",
  },
  {
    identifier: "com.apple.eloquence.es-ES.Flo",
    language: "es-ES",
    name: "Flo",
    quality: "Default",
  },
  {
    identifier: "com.apple.voice.compact.es-ES.Monica",
    language: "es-ES",
    name: "Mónica",
    quality: "Default",
  },
  {
    identifier: "com.apple.eloquence.es-ES.Eddy",
    language: "es-ES",
    name: "Eddy",
    quality: "Default",
  },
  {
    identifier: "com.apple.eloquence.es-ES.Reed",
    language: "es-ES",
    name: "Reed",
    quality: "Default",
  },
  {
    identifier: "com.apple.eloquence.es-MX.Rocko",
    language: "es-MX",
    name: "Rocko",
    quality: "Default",
  },
  {
    identifier: "com.apple.voice.compact.es-MX.Paulina",
    language: "es-MX",
    name: "Paulina",
    quality: "Default",
  },
  {
    identifier: "com.apple.eloquence.es-MX.Flo",
    language: "es-MX",
    name: "Flo",
    quality: "Default",
  },
  {
    identifier: "com.apple.eloquence.es-MX.Sandy",
    language: "es-MX",
    name: "Sandy",
    quality: "Default",
  },
  {
    identifier: "com.apple.eloquence.es-MX.Eddy",
    language: "es-MX",
    name: "Eddy",
    quality: "Default",
  },
  {
    identifier: "com.apple.eloquence.es-MX.Shelley",
    language: "es-MX",
    name: "Shelley",
    quality: "Default",
  },
  {
    identifier: "com.apple.eloquence.es-MX.Grandma",
    language: "es-MX",
    name: "Grandma",
    quality: "Default",
  },
  {
    identifier: "com.apple.eloquence.es-MX.Reed",
    language: "es-MX",
    name: "Reed",
    quality: "Default",
  },
  {
    identifier: "com.apple.eloquence.es-MX.Grandpa",
    language: "es-MX",
    name: "Grandpa",
    quality: "Default",
  },
  {
    identifier: "com.apple.eloquence.fi-FI.Shelley",
    language: "fi-FI",
    name: "Shelley",
    quality: "Default",
  },
  {
    identifier: "com.apple.eloquence.fi-FI.Grandma",
    language: "fi-FI",
    name: "Grandma",
    quality: "Default",
  },
  {
    identifier: "com.apple.eloquence.fi-FI.Grandpa",
    language: "fi-FI",
    name: "Grandpa",
    quality: "Default",
  },
  {
    identifier: "com.apple.eloquence.fi-FI.Sandy",
    language: "fi-FI",
    name: "Sandy",
    quality: "Default",
  },
  {
    identifier: "com.apple.voice.compact.fi-FI.Satu",
    language: "fi-FI",
    name: "Satu",
    quality: "Default",
  },
  {
    identifier: "com.apple.eloquence.fi-FI.Eddy",
    language: "fi-FI",
    name: "Eddy",
    quality: "Default",
  },
  {
    identifier: "com.apple.eloquence.fi-FI.Rocko",
    language: "fi-FI",
    name: "Rocko",
    quality: "Default",
  },
  {
    identifier: "com.apple.eloquence.fi-FI.Reed",
    language: "fi-FI",
    name: "Reed",
    quality: "Default",
  },
  {
    identifier: "com.apple.eloquence.fi-FI.Flo",
    language: "fi-FI",
    name: "Flo",
    quality: "Default",
  },
  {
    identifier: "com.apple.eloquence.fr-CA.Shelley",
    language: "fr-CA",
    name: "Shelley",
    quality: "Default",
  },
  {
    identifier: "com.apple.eloquence.fr-CA.Grandma",
    language: "fr-CA",
    name: "Grandma",
    quality: "Default",
  },
  {
    identifier: "com.apple.eloquence.fr-CA.Grandpa",
    language: "fr-CA",
    name: "Grandpa",
    quality: "Default",
  },
  {
    identifier: "com.apple.eloquence.fr-CA.Rocko",
    language: "fr-CA",
    name: "Rocko",
    quality: "Default",
  },
  {
    identifier: "com.apple.eloquence.fr-CA.Eddy",
    language: "fr-CA",
    name: "Eddy",
    quality: "Default",
  },
  {
    identifier: "com.apple.eloquence.fr-CA.Reed",
    language: "fr-CA",
    name: "Reed",
    quality: "Default",
  },
  {
    identifier: "com.apple.voice.compact.fr-CA.Amelie",
    language: "fr-CA",
    name: "Amélie",
    quality: "Default",
  },
  {
    identifier: "com.apple.eloquence.fr-CA.Flo",
    language: "fr-CA",
    name: "Flo",
    quality: "Default",
  },
  {
    identifier: "com.apple.eloquence.fr-CA.Sandy",
    language: "fr-CA",
    name: "Sandy",
    quality: "Default",
  },
  {
    identifier: "com.apple.eloquence.fr-FR.Grandma",
    language: "fr-FR",
    name: "Grandma",
    quality: "Default",
  },
  {
    identifier: "com.apple.eloquence.fr-FR.Flo",
    language: "fr-FR",
    name: "Flo",
    quality: "Default",
  },
  {
    identifier: "com.apple.eloquence.fr-FR.Rocko",
    language: "fr-FR",
    name: "Rocko",
    quality: "Default",
  },
  {
    identifier: "com.apple.eloquence.fr-FR.Grandpa",
    language: "fr-FR",
    name: "Grandpa",
    quality: "Default",
  },
  {
    identifier: "com.apple.eloquence.fr-FR.Sandy",
    language: "fr-FR",
    name: "Sandy",
    quality: "Default",
  },
  {
    identifier: "com.apple.eloquence.fr-FR.Eddy",
    language: "fr-FR",
    name: "Eddy",
    quality: "Default",
  },
  {
    identifier: "com.apple.ttsbundle.siri_Daniel_fr-FR_compact",
    language: "fr-FR",
    name: "Daniel",
    quality: "Default",
  },
  {
    identifier: "com.apple.voice.compact.fr-FR.Thomas",
    language: "fr-FR",
    name: "Thomas",
    quality: "Default",
  },
  {
    identifier: "com.apple.eloquence.fr-FR.Jacques",
    language: "fr-FR",
    name: "Jacques",
    quality: "Default",
  },
  {
    identifier: "com.apple.ttsbundle.siri_Marie_fr-FR_compact",
    language: "fr-FR",
    name: "Marie",
    quality: "Default",
  },
  {
    identifier: "com.apple.eloquence.fr-FR.Shelley",
    language: "fr-FR",
    name: "Shelley",
    quality: "Default",
  },
  {
    identifier: "com.apple.voice.compact.he-IL.Carmit",
    language: "he-IL",
    name: "Carmit",
    quality: "Default",
  },
  {
    identifier: "com.apple.voice.enhanced.hi-IN.Lekha",
    language: "hi-IN",
    name: "Lekha (Enhanced)",
    quality: "Enhanced",
  },
  {
    identifier: "com.apple.voice.compact.hi-IN.Lekha",
    language: "hi-IN",
    name: "Lekha",
    quality: "Default",
  },
  {
    identifier: "com.apple.voice.compact.hr-HR.Lana",
    language: "hr-HR",
    name: "Lana",
    quality: "Default",
  },
  {
    identifier: "com.apple.voice.compact.hu-HU.Mariska",
    language: "hu-HU",
    name: "Tünde",
    quality: "Default",
  },
  {
    identifier: "com.apple.voice.compact.id-ID.Damayanti",
    language: "id-ID",
    name: "Damayanti",
    quality: "Default",
  },
  {
    identifier: "com.apple.eloquence.it-IT.Eddy",
    language: "it-IT",
    name: "Eddy",
    quality: "Default",
  },
  {
    identifier: "com.apple.eloquence.it-IT.Sandy",
    language: "it-IT",
    name: "Sandy",
    quality: "Default",
  },
  {
    identifier: "com.apple.eloquence.it-IT.Reed",
    language: "it-IT",
    name: "Reed",
    quality: "Default",
  },
  {
    identifier: "com.apple.eloquence.it-IT.Shelley",
    language: "it-IT",
    name: "Shelley",
    quality: "Default",
  },
  {
    identifier: "com.apple.eloquence.it-IT.Grandma",
    language: "it-IT",
    name: "Grandma",
    quality: "Default",
  },
  {
    identifier: "com.apple.eloquence.it-IT.Grandpa",
    language: "it-IT",
    name: "Grandpa",
    quality: "Default",
  },
  {
    identifier: "com.apple.eloquence.it-IT.Flo",
    language: "it-IT",
    name: "Flo",
    quality: "Default",
  },
  {
    identifier: "com.apple.eloquence.it-IT.Rocko",
    language: "it-IT",
    name: "Rocko",
    quality: "Default",
  },
  {
    identifier: "com.apple.voice.compact.it-IT.Alice",
    language: "it-IT",
    name: "Alice",
    quality: "Default",
  },
  {
    identifier: "com.apple.ttsbundle.siri_O-ren_ja-JP_compact",
    language: "ja-JP",
    name: "O-ren",
    quality: "Default",
  },
  {
    identifier: "com.apple.voice.compact.ja-JP.Kyoko",
    language: "ja-JP",
    name: "Kyoko",
    quality: "Default",
  },
  {
    identifier: "com.apple.ttsbundle.siri_Hattori_ja-JP_compact",
    language: "ja-JP",
    name: "Hattori",
    quality: "Default",
  },
  {
    identifier: "com.apple.voice.compact.ko-KR.Yuna",
    language: "ko-KR",
    name: "Yuna",
    quality: "Default",
  },
  {
    identifier: "com.apple.voice.compact.ms-MY.Amira",
    language: "ms-MY",
    name: "Amira",
    quality: "Default",
  },
  {
    identifier: "com.apple.voice.compact.nb-NO.Nora",
    language: "nb-NO",
    name: "Nora",
    quality: "Default",
  },
  {
    identifier: "com.apple.voice.compact.nl-BE.Ellen",
    language: "nl-BE",
    name: "Ellen",
    quality: "Default",
  },
  {
    identifier: "com.apple.voice.compact.nl-NL.Xander",
    language: "nl-NL",
    name: "Xander",
    quality: "Default",
  },
  {
    identifier: "com.apple.voice.compact.pl-PL.Zosia",
    language: "pl-PL",
    name: "Zosia",
    quality: "Default",
  },
  {
    identifier: "com.apple.eloquence.pt-BR.Reed",
    language: "pt-BR",
    name: "Reed",
    quality: "Default",
  },
  {
    identifier: "com.apple.voice.compact.pt-BR.Luciana",
    language: "pt-BR",
    name: "Luciana",
    quality: "Default",
  },
  {
    identifier: "com.apple.eloquence.pt-BR.Shelley",
    language: "pt-BR",
    name: "Shelley",
    quality: "Default",
  },
  {
    identifier: "com.apple.eloquence.pt-BR.Grandma",
    language: "pt-BR",
    name: "Grandma",
    quality: "Default",
  },
  {
    identifier: "com.apple.eloquence.pt-BR.Grandpa",
    language: "pt-BR",
    name: "Grandpa",
    quality: "Default",
  },
  {
    identifier: "com.apple.eloquence.pt-BR.Rocko",
    language: "pt-BR",
    name: "Rocko",
    quality: "Default",
  },
  {
    identifier: "com.apple.eloquence.pt-BR.Flo",
    language: "pt-BR",
    name: "Flo",
    quality: "Default",
  },
  {
    identifier: "com.apple.eloquence.pt-BR.Sandy",
    language: "pt-BR",
    name: "Sandy",
    quality: "Default",
  },
  {
    identifier: "com.apple.eloquence.pt-BR.Eddy",
    language: "pt-BR",
    name: "Eddy",
    quality: "Default",
  },
  {
    identifier: "com.apple.voice.compact.pt-PT.Joana",
    language: "pt-PT",
    name: "Joana",
    quality: "Default",
  },
  {
    identifier: "com.apple.voice.compact.ro-RO.Ioana",
    language: "ro-RO",
    name: "Ioana",
    quality: "Default",
  },
  {
    identifier: "com.apple.voice.compact.ru-RU.Milena",
    language: "ru-RU",
    name: "Milena",
    quality: "Default",
  },
  {
    identifier: "com.apple.voice.compact.sk-SK.Laura",
    language: "sk-SK",
    name: "Laura",
    quality: "Default",
  },
  {
    identifier: "com.apple.voice.compact.sv-SE.Alva",
    language: "sv-SE",
    name: "Alva",
    quality: "Default",
  },
  {
    identifier: "com.apple.voice.compact.th-TH.Kanya",
    language: "th-TH",
    name: "Kanya",
    quality: "Default",
  },
  {
    identifier: "com.apple.voice.compact.tr-TR.Yelda",
    language: "tr-TR",
    name: "Yelda",
    quality: "Default",
  },
  {
    identifier: "com.apple.voice.compact.uk-UA.Lesya",
    language: "uk-UA",
    name: "Lesya",
    quality: "Default",
  },
  {
    identifier: "com.apple.voice.compact.vi-VN.Linh",
    language: "vi-VN",
    name: "Linh",
    quality: "Default",
  },
  {
    identifier: "com.apple.ttsbundle.siri_Li-mu_zh-CN_compact",
    language: "zh-CN",
    name: "Li-mu",
    quality: "Default",
  },
  {
    identifier: "com.apple.voice.compact.zh-CN.Tingting",
    language: "zh-CN",
    name: "Tingting",
    quality: "Default",
  },
  {
    identifier: "com.apple.ttsbundle.siri_Yu-shu_zh-CN_compact",
    language: "zh-CN",
    name: "Yu-shu",
    quality: "Default",
  },
  {
    identifier: "com.apple.voice.compact.zh-HK.Sinji",
    language: "zh-HK",
    name: "Sinji",
    quality: "Default",
  },
  {
    identifier: "com.apple.voice.compact.zh-TW.Meijia",
    language: "zh-TW",
    name: "Meijia",
    quality: "Default",
  },
  {
    identifier: "com.apple.speech.synthesis.voice.Alex",
    language: "en-US",
    name: "Alex",
    quality: "Enhanced",
  },
];
